In [8]:
import numpy as np

np.arange(5,13,2)

array([ 5,  7,  9, 11])

In [26]:
l1 = np.arange(10)
type(l1)

numpy.ndarray

In [27]:
#Implementing .ndim 
l1.ndim

1

In [28]:
(np.__version__)

'1.19.2'

In [29]:
# i am not using Print Command as we know this also works without print and its cool !

In [31]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.full((1, 2,3), True, dtype=bool)

array([[[ True,  True,  True],
        [ True,  True,  True]]])

In [41]:
# extract the ODD numbers
oddnumberl = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

oddnumberl[oddnumberl % 2 == 1]

array([1, 3, 5, 7, 9])

In [62]:
#add any value into list
addval = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
addval[addval % 2 == 1] 
addval

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
#item without affecting the original array
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [68]:
#reshape an array
arr = np.arange(10)
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [69]:
#stack two arrays vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [70]:
#stack two arrays horizontally
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [71]:
#generate custom sequences in numpy without hardcoding
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [73]:
#common items between two python numpy arrays?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [74]:
#remove from one array those items that exist in another?
x = np.array([1,2,3,4,5])
y = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 3, 5, 6])

In [75]:
#positions where elements of two arrays match?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

In [77]:
#extract all numbers between a given range from a numpy array?
a = np.array([2, 6, 1, 9, 10, 3, 27])
a = np.arange(15)
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 5,  6,  7,  8,  9, 10])

In [79]:
#make a python function that handles scalars to work on numpy arrays?

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

In [82]:
#swap two columns in a 2d numpy array?
arr = np.arange(9).reshape(3,3)

arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [81]:
#swap two rows in a 2d numpy array?
arr = np.arange(9).reshape(3,3)
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [87]:
#reverse the rows of a 2D array?
arr = np.arange(9).reshape(3,3)

arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [84]:
#reverse the columns of a 2D array?
arr = np.arange(9).reshape(3,3)

arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [86]:
#create a 2D array containing random floats between 5 and 10?
arr = np.arange(9).reshape(3,3)

rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
rand_arr

array([[7.82126409, 7.17139198, 6.40350327],
       [6.5812872 , 5.36601758, 7.37943641],
       [8.17294455, 9.03383923, 8.79781262],
       [7.56983884, 8.5979272 , 9.85008293],
       [8.89958745, 9.92991892, 7.24058142]])

In [88]:
#print only 3 decimal places in python numpy array?

rand_arr = np.random.random((5,3))

rand_arr[:4]

array([[0.41582262, 0.3202832 , 0.80145746],
       [0.48748525, 0.60404808, 0.58562231],
       [0.50272566, 0.34808838, 0.818483  ],
       [0.77548174, 0.88302392, 0.64421077]])

In [90]:
# REshapping
a = np.arange(15).reshape(3, 5)

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [91]:
a.shape

(3, 5)

In [92]:
a.dtype.name

'int64'

In [93]:
a.itemsize

8

In [94]:
a.size

15

In [95]:
type(a)

numpy.ndarray